title: Wilco Quest Builder
description: A documentation website for Wilco's Quest Builder
logo: "/assets/images/logo.png"
theme: just-the-docs

url: https://wilco-docs.github.io

aux_links:
  Get Started: https://app.wilco.gg  
